# Generated by Django 5.2.7 on 2026-01-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_recurringexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='reminder_active',
            field=models.BooleanField(default=True),
        ),
    ]
