# Generated by Django 5.2.7 on 2026-01-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_recurringexpense_reminder_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.AddField(
            model_name='entry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(blank=True, choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Neutral', 'Neutral'), ('Excited', 'Excited'), ('Anxious', 'Anxious')], max_length=50),
        ),
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
