# Generated by Django 5.2.7 on 2026-01-21 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_tag_alter_entry_options_entry_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
